---
- hosts: all
  roles:
    - role: publish-windows-containers
      registries:
        - host: "10.84.5.81:5000"
          protocol: http
        - host: "index.docker.io/opencontrailnightly"
          protocol: https
